<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\CustomerAddress;
use App\Models\CustomerDetails;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CustomerDataSeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            // 1-10: Industrial Manufacturing & Engineering
            [
                'company' => 'Titan Forge Precision Engineering Ltd',
                'first' => 'David', 'last' => 'Kensington', 'phone' => '0121 555 0101', 'mobile' => '07700 901101',
                'email' => 'd.kensington@titanforge.co.uk',
                'city' => 'Birmingham', 'county' => 'West Midlands', 'postcode' => 'B6 7AA',
                'billing_street' => 'Titan Industrial Estate, Cheston Road, Aston',
                'site_street' => 'Titan Plant 1 Heavy Foundry, Holford Drive, Perry Barr',
                'assets' => 2400000.00, 'liabilities' => 850000.00, 'cash' => 380000.00,
            ],
            [
                'company' => 'Caledonia Steel & Fabrication Ltd',
                'first' => 'Hamish', 'last' => 'Campbell', 'phone' => '0141 555 0102', 'mobile' => '07700 901102',
                'email' => 'hcampbell@caledoniasteel.co.uk',
                'city' => 'Glasgow', 'county' => 'Lanarkshire', 'postcode' => 'G51 4SE',
                'billing_street' => 'Clyde Structural Works, Govan Road',
                'site_street' => 'Clyde Yard 3 Steel Processing, Shieldhall Quay',
                'assets' => 3800000.00, 'liabilities' => 1200000.00, 'cash' => 540000.00,
            ],
            [
                'company' => 'Vanguard Aerospace Components Ltd',
                'first' => 'Victoria', 'last' => 'Pemberton', 'phone' => '0117 555 0103', 'mobile' => '07700 901103',
                'email' => 'v.pemberton@vanguardaero.co.uk',
                'city' => 'Bristol', 'county' => 'Gloucestershire', 'postcode' => 'BS34 7QZ',
                'billing_street' => 'Filton Aerospace Centre, Golf Course Lane',
                'site_street' => 'Hangar 4 Cleanroom Assembly, Pegasus Park',
                'assets' => 5600000.00, 'liabilities' => 1750000.00, 'cash' => 890000.00,
            ],
            [
                'company' => 'Severn Valley Castings Ltd',
                'first' => 'Thomas', 'last' => 'Glover', 'phone' => '01452 555 0104', 'mobile' => '07700 901104',
                'email' => 'tglover@severncastings.co.uk',
                'city' => 'Gloucester', 'county' => 'Gloucestershire', 'postcode' => 'GL2 5EE',
                'billing_street' => 'Severnside Foundry Park, Hempsted Lane',
                'site_street' => 'Melting Works Bay 2, Sudmeadow Road',
                'assets' => 1650000.00, 'liabilities' => 620000.00, 'cash' => 240000.00,
            ],
            [
                'company' => 'Yorkshire Heavy Rotors & Turbines Ltd',
                'first' => 'Arthur', 'last' => 'Ackroyd', 'phone' => '0114 555 0105', 'mobile' => '07700 901105',
                'email' => 'a.ackroyd@yorkshirerotors.co.uk',
                'city' => 'Sheffield', 'county' => 'South Yorkshire', 'postcode' => 'S9 2RX',
                'billing_street' => 'Don Valley Technology Park, Carbrook Hall Road',
                'site_street' => 'Machining Bay 5, Attercliffe Common',
                'assets' => 4100000.00, 'liabilities' => 1400000.00, 'cash' => 610000.00,
            ],
            [
                'company' => 'Pennine Tool & Die Solutions Ltd',
                'first' => 'Nigel', 'last' => 'Braithwaite', 'phone' => '01282 555 0106', 'mobile' => '07700 901106',
                'email' => 'nbraithwaite@penninetool.co.uk',
                'city' => 'Burnley', 'county' => 'Lancashire', 'postcode' => 'BB11 5UB',
                'billing_street' => 'Rossendale Road Industrial Estate, Billington Road',
                'site_street' => 'CNC Milling Facility, Network 65 Business Park',
                'assets' => 1450000.00, 'liabilities' => 480000.00, 'cash' => 195000.00,
            ],
            [
                'company' => 'Mersey Maritime Propulsion Ltd',
                'first' => 'Sean', 'last' => 'Callaghan', 'phone' => '0151 555 0107', 'mobile' => '07700 901107',
                'email' => 'scallaghan@merseymaritime.co.uk',
                'city' => 'Liverpool', 'county' => 'Merseyside', 'postcode' => 'L3 4FP',
                'billing_street' => 'Royal Liver Building, Pier Head',
                'site_street' => 'Birkenhead Marine Workshop, Abbey Road, Wirral',
                'assets' => 2900000.00, 'liabilities' => 950000.00, 'cash' => 430000.00,
            ],
            [
                'company' => 'Thames Laser Cutting & CNC Ltd',
                'first' => 'Oliver', 'last' => 'Weston', 'phone' => '01322 555 0108', 'mobile' => '07700 901108',
                'email' => 'oweston@thameslaser.co.uk',
                'city' => 'Dartford', 'county' => 'Kent', 'postcode' => 'DA1 5FW',
                'billing_street' => 'Crossways Business Park, Clipper Boulevard',
                'site_street' => 'Laser Bay 1, Galleon Boulevard',
                'assets' => 1850000.00, 'liabilities' => 590000.00, 'cash' => 280000.00,
            ],
            [
                'company' => 'Midlands Sheet Metal Fabrication Ltd',
                'first' => 'Gary', 'last' => 'Hickman', 'phone' => '01384 555 0109', 'mobile' => '07700 901109',
                'email' => 'ghickman@midlandssheetmetal.co.uk',
                'city' => 'Dudley', 'county' => 'West Midlands', 'postcode' => 'DY2 8PT',
                'billing_street' => 'Cradley Heath Business Park, Overend Road',
                'site_street' => 'Press Brake Works, Peartree Lane',
                'assets' => 1200000.00, 'liabilities' => 410000.00, 'cash' => 170000.00,
            ],
            [
                'company' => 'Highland Hydraulics & Cylinders Ltd',
                'first' => 'Ewan', 'last' => 'Fraser', 'phone' => '01463 555 0110', 'mobile' => '07700 901110',
                'email' => 'efraser@highlandhydraulics.co.uk',
                'city' => 'Inverness', 'county' => 'Highlands', 'postcode' => 'IV1 1SY',
                'billing_street' => 'Longman Industrial Estate, Harbour Road',
                'site_street' => 'Hydraulic Overhaul Bay, Stadium Road',
                'assets' => 1350000.00, 'liabilities' => 390000.00, 'cash' => 210000.00,
            ],

            // 11-20: Logistics, Freight & Cold Chain Storage
            [
                'company' => 'North Star Freight Logistics UK',
                'first' => 'Claire', 'last' => 'Fairfax', 'phone' => '0161 555 0111', 'mobile' => '07700 901111',
                'email' => 'cfairfax@northstarfreight.co.uk',
                'city' => 'Manchester', 'county' => 'Greater Manchester', 'postcode' => 'M90 5DL',
                'billing_street' => 'World Freight Terminal, Manchester Airport',
                'site_street' => 'Depot 8 High-Bay Transshipment Hub, Avro Way',
                'assets' => 4800000.00, 'liabilities' => 1650000.00, 'cash' => 720000.00,
            ],
            [
                'company' => 'Thames Gateway Container Depot Ltd',
                'first' => 'Raymond', 'last' => 'Cross', 'phone' => '01375 555 0112', 'mobile' => '07700 901112',
                'email' => 'rcross@thamesgatewaydepot.co.uk',
                'city' => 'Stanford-le-Hope', 'county' => 'Essex', 'postcode' => 'SS17 9PD',
                'billing_street' => 'London Gateway Logistics Park, North Sea Avenue',
                'site_street' => 'Reefer Container Staging Bay 4, Terminal Drive',
                'assets' => 6200000.00, 'liabilities' => 2100000.00, 'cash' => 950000.00,
            ],
            [
                'company' => 'Solent Maritime Cargo Services Ltd',
                'first' => 'Simon', 'last' => 'Trelawney', 'phone' => '02380 555 0113', 'mobile' => '07700 901113',
                'email' => 'strelawney@solentcargo.co.uk',
                'city' => 'Southampton', 'county' => 'Hampshire', 'postcode' => 'SO15 1HA',
                'billing_street' => 'Ocean Gate, Atlantic Way',
                'site_street' => 'Western Docks Berth 201 Cargo Transit Shed',
                'assets' => 3400000.00, 'liabilities' => 1100000.00, 'cash' => 520000.00,
            ],
            [
                'company' => 'Midlands Intermodal Distribution Ltd',
                'first' => 'Karen', 'last' => 'Pritchard', 'phone' => '01332 555 0114', 'mobile' => '07700 901114',
                'email' => 'kpritchard@midlandsintermodal.co.uk',
                'city' => 'Derby', 'county' => 'Derbyshire', 'postcode' => 'DE74 2SA',
                'billing_street' => 'East Midlands Gateway, Logistics Consortium Way',
                'site_street' => 'Rail Freight Terminal Warehouse 2',
                'assets' => 5100000.00, 'liabilities' => 1800000.00, 'cash' => 780000.00,
            ],
            [
                'company' => 'Apex Temperature Controlled Storage Ltd',
                'first' => 'Trevor', 'last' => 'Langham', 'phone' => '01733 555 0115', 'mobile' => '07700 901115',
                'email' => 'tlangham@apexcoldstorage.co.uk',
                'city' => 'Peterborough', 'county' => 'Cambridgeshire', 'postcode' => 'PE2 6XU',
                'billing_street' => 'Orton Southgate Commercial Park, Bakewell Road',
                'site_street' => 'Sub-Zero Blast Freezing Facility 3, Stapledon Road',
                'assets' => 3900000.00, 'liabilities' => 1350000.00, 'cash' => 490000.00,
            ],
            [
                'company' => 'Severnside Haulage & Pallet Express Ltd',
                'first' => 'Darren', 'last' => 'Bridges', 'phone' => '01633 555 0116', 'mobile' => '07700 901116',
                'email' => 'dbridges@severnsidehaulage.co.uk',
                'city' => 'Newport', 'county' => 'South Wales', 'postcode' => 'NP19 4QZ',
                'billing_street' => 'Queensway Meadows Industrial Estate, Esperanto Way',
                'site_street' => 'Fleet Maintenance Depot & Crossdock, Langland Park',
                'assets' => 2200000.00, 'liabilities' => 780000.00, 'cash' => 310000.00,
            ],
            [
                'company' => 'Humber Bulk Liquid Logistics Ltd',
                'first' => 'Ian', 'last' => 'Pickering', 'phone' => '01482 555 0117', 'mobile' => '07700 901117',
                'email' => 'ipickering@humberbulk.co.uk',
                'city' => 'Hull', 'county' => 'East Yorkshire', 'postcode' => 'HU9 5PX',
                'billing_street' => 'King George Dock Commercial House, Hedon Road',
                'site_street' => 'Tank Storage Farm Terminal 7, Marfleet Creek',
                'assets' => 4300000.00, 'liabilities' => 1500000.00, 'cash' => 640000.00,
            ],
            [
                'company' => 'Trans-Pennine Express Distribution Ltd',
                'first' => 'Philip', 'last' => 'Sutcliffe', 'phone' => '01422 555 0118', 'mobile' => '07700 901118',
                'email' => 'psutcliffe@transpennine.co.uk',
                'city' => 'Halifax', 'county' => 'West Yorkshire', 'postcode' => 'HX3 9EZ',
                'billing_street' => 'Lowfields Business Park, Elland',
                'site_street' => 'Depot 5 Northern Sortation Facility, Ainley Top',
                'assets' => 2750000.00, 'liabilities' => 910000.00, 'cash' => 395000.00,
            ],
            [
                'company' => 'Caledonian Cold Chain Logistics Ltd',
                'first' => 'Gordon', 'last' => 'McIntyre', 'phone' => '01224 555 0119', 'mobile' => '07700 901119',
                'email' => 'gmcintyre@caledoniancold.co.uk',
                'city' => 'Aberdeen', 'county' => 'Aberdeenshire', 'postcode' => 'AB12 3LH',
                'billing_street' => 'East Tullos Industrial Estate, Craigshaw Drive',
                'site_street' => 'Offshore Catering Cold Storage Unit 4, Greenwell Road',
                'assets' => 3100000.00, 'liabilities' => 1050000.00, 'cash' => 450000.00,
            ],
            [
                'company' => 'Anglia Regional Fulfillment Hub Ltd',
                'first' => 'Brian', 'last' => 'Cranston', 'phone' => '01603 555 0120', 'mobile' => '07700 901120',
                'email' => 'bcranston@angliafulfillment.co.uk',
                'city' => 'Norwich', 'county' => 'Norfolk', 'postcode' => 'NR6 6JA',
                'billing_street' => 'Broadland Business Park, Meridian Way',
                'site_street' => 'E-Commerce Picking Warehouse 1B, Mile Cross Lane',
                'assets' => 1950000.00, 'liabilities' => 640000.00, 'cash' => 285000.00,
            ],

            // 21-30: Hospitality, Luxury Hotels & Event Venues
            [
                'company' => 'Kensington Palace Gardens Hotels Ltd',
                'first' => 'Charles', 'last' => 'Montgomery', 'phone' => '0207 555 0121', 'mobile' => '07700 901121',
                'email' => 'cmontgomery@kensingtonhotels.co.uk',
                'city' => 'London', 'county' => 'Greater London', 'postcode' => 'W8 4PT',
                'billing_street' => 'The Kensington Royal Suites, 14 De Vere Gardens',
                'site_street' => 'Hotel Main Building & Spa Pavilion, Kensington High St',
                'assets' => 8900000.00, 'liabilities' => 2900000.00, 'cash' => 1400000.00,
            ],
            [
                'company' => 'The Royal Balmoral Hotel Edinburgh plc',
                'first' => 'Alistair', 'last' => 'Drummond', 'phone' => '0131 555 0122', 'mobile' => '07700 901122',
                'email' => 'adrummond@royalbalmoral.co.uk',
                'city' => 'Edinburgh', 'county' => 'Midlothian', 'postcode' => 'EH1 1BB',
                'billing_street' => '1 Princes Street Executive Chambers',
                'site_street' => 'Grand Dining Hall & Victorian Ballroom, North Bridge Wing',
                'assets' => 7400000.00, 'liabilities' => 2400000.00, 'cash' => 1100000.00,
            ],
            [
                'company' => 'Windermere Lakeside Manor & Spa Ltd',
                'first' => 'Gemma', 'last' => 'Barrow', 'phone' => '015394 555 0123', 'mobile' => '07700 901123',
                'email' => 'gbarrow@windermeremanor.co.uk',
                'city' => 'Bowness-on-Windermere', 'county' => 'Cumbria', 'postcode' => 'LA23 3HH',
                'billing_street' => 'Lakeside Drive Country Club',
                'site_street' => 'Thermal Hydrotherapy Suite & Lodges, Rayrigg Road',
                'assets' => 4500000.00, 'liabilities' => 1350000.00, 'cash' => 620000.00,
            ],
            [
                'company' => 'Cotswolds Heritage Boutique Inns Ltd',
                'first' => 'Rupert', 'last' => 'Chawton', 'phone' => '01285 555 0124', 'mobile' => '07700 901124',
                'email' => 'rchawton@cotswoldinns.co.uk',
                'city' => 'Cirencester', 'county' => 'Gloucestershire', 'postcode' => 'GL7 2NX',
                'billing_street' => 'The Old Wool Hall, Market Place',
                'site_street' => 'The Swan Inn & Coaching House, Bibury',
                'assets' => 3200000.00, 'liabilities' => 980000.00, 'cash' => 460000.00,
            ],
            [
                'company' => 'Mayfair Premier Banqueting & Suites Ltd',
                'first' => 'Julian', 'last' => 'Sinclair', 'phone' => '0207 555 0125', 'mobile' => '07700 901125',
                'email' => 'jsinclair@mayfairsuites.co.uk',
                'city' => 'London', 'county' => 'Greater London', 'postcode' => 'W1K 7TN',
                'billing_street' => 'Park Lane Corporate Offices, 88 Park Lane',
                'site_street' => 'The Great Ballroom & Executive Mezzanine, Curzon Street',
                'assets' => 6800000.00, 'liabilities' => 2200000.00, 'cash' => 1050000.00,
            ],
            [
                'company' => 'St Andrews Links Golf Resort Ltd',
                'first' => 'Douglas', 'last' => 'MacIntosh', 'phone' => '01334 555 0126', 'mobile' => '07700 901126',
                'email' => 'dmacintosh@standrewsresort.co.uk',
                'city' => 'St Andrews', 'county' => 'Fife', 'postcode' => 'KY16 9XL',
                'billing_street' => 'Clubhouse Way, Old Course Pavilion',
                'site_street' => 'Lodge Suites & Pro Clubhouse Plantroom, Links Road',
                'assets' => 5900000.00, 'liabilities' => 1800000.00, 'cash' => 880000.00,
            ],
            [
                'company' => 'Cambridge Academic Conference Centre Ltd',
                'first' => 'Penelope', 'last' => 'Vaughan', 'phone' => '01223 555 0127', 'mobile' => '07700 901127',
                'email' => 'pvaughan@cambridgeconferences.co.uk',
                'city' => 'Cambridge', 'county' => 'Cambridgeshire', 'postcode' => 'CB2 1ST',
                'billing_street' => 'Trumpington Street Lecture Hall Complex',
                'site_street' => 'Sedgwick Auditorium & Dining Commons, Downing Site',
                'assets' => 4100000.00, 'liabilities' => 1250000.00, 'cash' => 570000.00,
            ],
            [
                'company' => 'Oxford Manor Hotel & Conference Suites Ltd',
                'first' => 'Hugh', 'last' => 'Kingsley', 'phone' => '01865 555 0128', 'mobile' => '07700 901128',
                'email' => 'hkingsley@oxfordmanor.co.uk',
                'city' => 'Oxford', 'county' => 'Oxfordshire', 'postcode' => 'OX2 6NN',
                'billing_street' => 'Banbury Road Manor House',
                'site_street' => 'Executive Garden Pavilion & Gym, Woodstock Road',
                'assets' => 3850000.00, 'liabilities' => 1150000.00, 'cash' => 520000.00,
            ],
            [
                'company' => 'York Minster Historic Inn Group Ltd',
                'first' => 'Hannah', 'last' => 'Beaumont', 'phone' => '01904 555 0129', 'mobile' => '07700 901129',
                'email' => 'hbeaumont@yorkinns.co.uk',
                'city' => 'York', 'county' => 'North Yorkshire', 'postcode' => 'YO1 7HH',
                'billing_street' => 'Stonegate Heritage Chambers, 22 Stonegate',
                'site_street' => 'The Black Swan Hotel & Cellar Kitchen, Peasholme Green',
                'assets' => 2900000.00, 'liabilities' => 880000.00, 'cash' => 410000.00,
            ],
            [
                'company' => 'Cardiff Bay Marina Hotel & Spa Ltd',
                'first' => 'Gareth', 'last' => 'Pugh', 'phone' => '02920 555 0130', 'mobile' => '07700 901130',
                'email' => 'gpugh@cardiffbayhotel.co.uk',
                'city' => 'Cardiff', 'county' => 'South Glamorgan', 'postcode' => 'CF10 4PA',
                'billing_street' => 'Bute Crescent Waterfront Suite',
                'site_street' => 'Hydro Spa, Pool Plantroom & Banquet Kitchen, Pierhead St',
                'assets' => 4700000.00, 'liabilities' => 1550000.00, 'cash' => 690000.00,
            ],

            // 31-40: Commercial Property, Facilities & Real Estate
            [
                'company' => 'Canary Wharf Executive Facilities Ltd',
                'first' => 'Andrew', 'last' => 'Whitworth', 'phone' => '0207 555 0131', 'mobile' => '07700 901131',
                'email' => 'awhitworth@canarywharffm.co.uk',
                'city' => 'London', 'county' => 'Greater London', 'postcode' => 'E14 5AB',
                'billing_street' => 'One Canada Square Tower Management, Level 28',
                'site_street' => 'Basement Substation & Central HVAC Chiller Room 4',
                'assets' => 11500000.00, 'liabilities' => 3800000.00, 'cash' => 1950000.00,
            ],
            [
                'company' => 'Manchester Spinningfields Commercial Management Ltd',
                'first' => 'Rebecca', 'last' => 'Hargreaves', 'phone' => '0161 555 0132', 'mobile' => '07700 901132',
                'email' => 'rhargreaves@spinningfieldsfm.co.uk',
                'city' => 'Manchester', 'county' => 'Greater Manchester', 'postcode' => 'M3 3EB',
                'billing_street' => '3 Hardman Square Commercial Estates',
                'site_street' => 'Tower A & B Plantrooms, Deansgate Gate',
                'assets' => 8400000.00, 'liabilities' => 2600000.00, 'cash' => 1250000.00,
            ],
            [
                'company' => 'Birmingham Colmore Row Property Asset Management plc',
                'first' => 'Jonathan', 'last' => 'Blythe', 'phone' => '0121 555 0133', 'mobile' => '07700 901133',
                'email' => 'jblythe@colmorerowfm.co.uk',
                'city' => 'Birmingham', 'county' => 'West Midlands', 'postcode' => 'B3 2AA',
                'billing_street' => '103 Colmore Row, Level 14',
                'site_street' => 'Roof Chiller Compound & Fire Pump House, Newhall Street',
                'assets' => 6900000.00, 'liabilities' => 2100000.00, 'cash' => 980000.00,
            ],
            [
                'company' => 'Leeds Wellington Place Real Estate Ltd',
                'first' => 'Timothy', 'last' => 'Brooke', 'phone' => '0113 555 0134', 'mobile' => '07700 901134',
                'email' => 'tbrooke@wellingtonplace.co.uk',
                'city' => 'Leeds', 'county' => 'West Yorkshire', 'postcode' => 'LS1 4AP',
                'billing_street' => '5 Wellington Place Estate Office',
                'site_street' => 'Building 6 Rooftop VRF & Ventilation Plant, Northern St',
                'assets' => 5200000.00, 'liabilities' => 1600000.00, 'cash' => 740000.00,
            ],
            [
                'company' => 'Bristol Temple Quay Commercial Estates Ltd',
                'first' => 'Jessica', 'last' => 'Rowe', 'phone' => '0117 555 0135', 'mobile' => '07700 901135',
                'email' => 'jrowe@templequayfm.co.uk',
                'city' => 'Bristol', 'county' => 'Somerset', 'postcode' => 'BS1 6EA',
                'billing_street' => 'Temple Quay House, 2 The Square',
                'site_street' => 'Harbourside Commercial Pavilion Plantroom, Friary Yard',
                'assets' => 4600000.00, 'liabilities' => 1400000.00, 'cash' => 670000.00,
            ],
            [
                'company' => 'Newcastle Quayside Developments Ltd',
                'first' => 'Malcolm', 'last' => 'Fenwick', 'phone' => '0191 555 0136', 'mobile' => '07700 901136',
                'email' => 'mfenwick@quaysidedevelopments.co.uk',
                'city' => 'Newcastle upon Tyne', 'county' => 'Tyne and Wear', 'postcode' => 'NE1 3DE',
                'billing_street' => 'Baltic Chambers, Broad Chare',
                'site_street' => 'Quayside Tower 2 Transformer Substation, Close Way',
                'assets' => 3800000.00, 'liabilities' => 1180000.00, 'cash' => 520000.00,
            ],
            [
                'company' => 'Belfast Titanic Quarter Commercial Estates Ltd',
                'first' => 'Declan', 'last' => 'O\'Connor', 'phone' => '02890 555 0137', 'mobile' => '07700 901137',
                'email' => 'doconnor@titanicquarterfm.co.uk',
                'city' => 'Belfast', 'county' => 'County Antrim', 'postcode' => 'BT3 9DT',
                'billing_street' => 'Titanic House, 6 Queens Road',
                'site_street' => 'Innovation Centre 2 HVAC & Energy Centre, Sydenham Rd',
                'assets' => 5100000.00, 'liabilities' => 1650000.00, 'cash' => 730000.00,
            ],
            [
                'company' => 'Edinburgh St James Quarter Property Management Ltd',
                'first' => 'Catriona', 'last' => 'Sinclair', 'phone' => '0131 555 0138', 'mobile' => '07700 901138',
                'email' => 'csinclair@stjamesquarter.co.uk',
                'city' => 'Edinburgh', 'county' => 'Midlothian', 'postcode' => 'EH1 3AD',
                'billing_street' => 'St James Quarter Commercial Suites',
                'site_street' => 'Central Retail Energy Centre & Boilers, Leith Street',
                'assets' => 9200000.00, 'liabilities' => 3100000.00, 'cash' => 1350000.00,
            ],
            [
                'company' => 'Southampton Ocean Village Marina Estates Ltd',
                'first' => 'Clive', 'last' => 'Sturgess', 'phone' => '02380 555 0139', 'mobile' => '07700 901139',
                'email' => 'csturgess@oceanvillagefm.co.uk',
                'city' => 'Southampton', 'county' => 'Hampshire', 'postcode' => 'SO14 3TL',
                'billing_street' => 'Ocean Way Commercial Offices, 4 Neptune Point',
                'site_street' => 'Marina Dockside Electrical Incomer, Channel Way',
                'assets' => 3400000.00, 'liabilities' => 1020000.00, 'cash' => 490000.00,
            ],
            [
                'company' => 'Milton Keynes Central Commercial Parks Ltd',
                'first' => 'Gary', 'last' => 'Thornfield', 'phone' => '01908 555 0140', 'mobile' => '07700 901140',
                'email' => 'gthornfield@mkcommercial.co.uk',
                'city' => 'Milton Keynes', 'county' => 'Buckinghamshire', 'postcode' => 'MK9 1BB',
                'billing_street' => 'Midsummer Boulevard Commercial House',
                'site_street' => 'Pinnacle Office Campus AHU Plantroom, Saxon Gate',
                'assets' => 4250000.00, 'liabilities' => 1320000.00, 'cash' => 610000.00,
            ],

            // 41-50: Retail Chains, Shopping Centres & Supermarkets
            [
                'company' => 'Westfield London Retail Management Ltd',
                'first' => 'Simon', 'last' => 'Goldstein', 'phone' => '0208 555 0141', 'mobile' => '07700 901141',
                'email' => 'sgoldstein@westfieldlondon.co.uk',
                'city' => 'London', 'county' => 'Greater London', 'postcode' => 'W12 7GF',
                'billing_street' => 'Centre Management Suite, Ariel Way, Shepherd\'s Bush',
                'site_street' => 'Atrium 3 Smoke Extraction & Sprinkler Pump House',
                'assets' => 14000000.00, 'liabilities' => 4500000.00, 'cash' => 2200000.00,
            ],
            [
                'company' => 'Trafford Centre Retail & Leisure Operations Ltd',
                'first' => 'Mark', 'last' => 'Holloway', 'phone' => '0161 555 0142', 'mobile' => '07700 901142',
                'email' => 'mholloway@traffordcentre.co.uk',
                'city' => 'Manchester', 'county' => 'Greater Manchester', 'postcode' => 'M17 8AA',
                'billing_street' => 'The Dome Operations Centre, Regent Crescent',
                'site_street' => 'Orient Food Court Extraction & Grease Interceptor Plant',
                'assets' => 12500000.00, 'liabilities' => 3900000.00, 'cash' => 1850000.00,
            ],
            [
                'company' => 'Bluewater Greenhithe Retail Management Ltd',
                'first' => 'Fiona', 'last' => 'Carrington', 'phone' => '01322 555 0143', 'mobile' => '07700 901143',
                'email' => 'fcarrington@bluewaterretail.co.uk',
                'city' => 'Greenhithe', 'county' => 'Kent', 'postcode' => 'DA9 9ST',
                'billing_street' => 'Bluewater Management Suite, The Village',
                'site_street' => 'Rose Gallery Roof Chiller Bank & Cooling Towers',
                'assets' => 11000000.00, 'liabilities' => 3600000.00, 'cash' => 1650000.00,
            ],
            [
                'company' => 'Meadowhall Sheffield Shopping Centre Ltd',
                'first' => 'Paul', 'last' => 'Dyson', 'phone' => '0114 555 0144', 'mobile' => '07700 901144',
                'email' => 'pdyson@meadowhallfm.co.uk',
                'city' => 'Sheffield', 'county' => 'South Yorkshire', 'postcode' => 'S9 1EP',
                'billing_street' => 'Centre Management Office, The Oasis',
                'site_street' => 'High Street Galleria AHU Air Handler Rooms',
                'assets' => 9800000.00, 'liabilities' => 3200000.00, 'cash' => 1450000.00,
            ],
            [
                'company' => 'Bullring & Grand Central Birmingham Ltd',
                'first' => 'Craig', 'last' => 'Stevenson', 'phone' => '0121 555 0145', 'mobile' => '07700 901145',
                'email' => 'cstevenson@bullringfm.co.uk',
                'city' => 'Birmingham', 'county' => 'West Midlands', 'postcode' => 'B5 4BU',
                'billing_street' => 'Estate Management Suite, Moor Street Link',
                'site_street' => 'Selfridges Service Yard & Switchgear Room B',
                'assets' => 10200000.00, 'liabilities' => 3400000.00, 'cash' => 1550000.00,
            ],
            [
                'company' => 'Metrocentre Gateshead Operations Ltd',
                'first' => 'Neil', 'last' => 'Armstrong', 'phone' => '0191 555 0146', 'mobile' => '07700 901146',
                'email' => 'narmstrong@metrocentrefm.co.uk',
                'city' => 'Gateshead', 'county' => 'Tyne and Wear', 'postcode' => 'NE11 9YG',
                'billing_street' => 'Metrocentre Management Office, Garden Corridor',
                'site_street' => 'Platinum Mall Rooftop Air Cooled Chillers',
                'assets' => 8700000.00, 'liabilities' => 2800000.00, 'cash' => 1300000.00,
            ],
            [
                'company' => 'Cabot Circus Bristol Commercial Properties Ltd',
                'first' => 'Leanne', 'last' => 'Tanner', 'phone' => '0117 555 0147', 'mobile' => '07700 901147',
                'email' => 'ltanner@cabotcircusfm.co.uk',
                'city' => 'Bristol', 'county' => 'Somerset', 'postcode' => 'BS1 3BX',
                'billing_street' => 'Management Suite, Glass Walk, Broadmead',
                'site_street' => 'Cinema Complex Air Handling & Fire Dampers, Bond St',
                'assets' => 6400000.00, 'liabilities' => 1950000.00, 'cash' => 920000.00,
            ],
            [
                'company' => 'Liverpool ONE Property Management Ltd',
                'first' => 'Gary', 'last' => 'O\'Halloran', 'phone' => '0151 555 0148', 'mobile' => '07700 901148',
                'email' => 'gohalloran@liverpoolonefm.co.uk',
                'city' => 'Liverpool', 'county' => 'Merseyside', 'postcode' => 'L1 8JQ',
                'billing_street' => '5 Wall Street Estate Management',
                'site_street' => 'South John Street Underground Loading Bay & Pumps',
                'assets' => 7600000.00, 'liabilities' => 2300000.00, 'cash' => 1100000.00,
            ],
            [
                'company' => 'Trinity Leeds Shopping Centre Operations Ltd',
                'first' => 'Stewart', 'last' => 'Rhodes', 'phone' => '0113 555 0149', 'mobile' => '07700 901149',
                'email' => 'srhodes@trinityleedsfm.co.uk',
                'city' => 'Leeds', 'county' => 'West Yorkshire', 'postcode' => 'LS1 5ER',
                'billing_street' => 'Trinity Management Offices, Albion Street',
                'site_street' => 'Glass Roof Automatic Ventilation Actuators, Briggate',
                'assets' => 7100000.00, 'liabilities' => 2200000.00, 'cash' => 1050000.00,
            ],
            [
                'company' => 'Silverburn Glasgow Retail Management Ltd',
                'first' => 'Kenneth', 'last' => 'Morrison', 'phone' => '0141 555 0150', 'mobile' => '07700 901150',
                'email' => 'kmorrison@silverburnfm.co.uk',
                'city' => 'Glasgow', 'county' => 'Renfrewshire', 'postcode' => 'G53 6QR',
                'billing_street' => 'Management Centre, Barrhead Road',
                'site_street' => 'Cinema & Restaurant Row Kitchen Extraction Ductwork',
                'assets' => 6900000.00, 'liabilities' => 2100000.00, 'cash' => 980000.00,
            ],

            // 51-60: Energy, Renewables, Solar & Utilities
            [
                'company' => 'Solent Solar Arrays & Battery Systems Ltd',
                'first' => 'Matthew', 'last' => 'Redman', 'phone' => '02392 555 0151', 'mobile' => '07700 901151',
                'email' => 'mredman@solentsolar.co.uk',
                'city' => 'Portsmouth', 'county' => 'Hampshire', 'postcode' => 'PO6 4TJ',
                'billing_street' => 'Lakeside North Harbour, Western Road',
                'site_street' => 'Langstone Harbour 250kW Solar Array & Inverters',
                'assets' => 3900000.00, 'liabilities' => 1200000.00, 'cash' => 580000.00,
            ],
            [
                'company' => 'Severn Biomass Energy Systems Ltd',
                'first' => 'Geoffrey', 'last' => 'Underwood', 'phone' => '01432 555 0152', 'mobile' => '07700 901152',
                'email' => 'gunderwood@severnbiomass.co.uk',
                'city' => 'Hereford', 'county' => 'Herefordshire', 'postcode' => 'HR2 6PR',
                'billing_street' => 'Rotherwas Industrial Estate, Holme Lacy Road',
                'site_street' => 'Biomass Boiler Plant & Woodchip Silo, Thorn Business Park',
                'assets' => 2800000.00, 'liabilities' => 950000.00, 'cash' => 410000.00,
            ],
            [
                'company' => 'Pennine Wind Farm Operations Ltd',
                'first' => 'Keith', 'last' => 'Broadbent', 'phone' => '01706 555 0153', 'mobile' => '07700 901153',
                'email' => 'kbroadbent@penninewind.co.uk',
                'city' => 'Rochdale', 'county' => 'Greater Manchester', 'postcode' => 'OL16 1NA',
                'billing_street' => 'Pennine Moor Commercial Offices, Yorkshire Street',
                'site_street' => 'Scout Moor Turbine Substation Control Room, Edenfield',
                'assets' => 5400000.00, 'liabilities' => 1700000.00, 'cash' => 820000.00,
            ],
            [
                'company' => 'Clyde Hydro Energy & Turbine Maintenance Ltd',
                'first' => 'Rory', 'last' => 'MacDougall', 'phone' => '01389 555 0154', 'mobile' => '07700 901154',
                'email' => 'rmacdougall@clydehydro.co.uk',
                'city' => 'Dumbarton', 'county' => 'Dunbartonshire', 'postcode' => 'G82 1RE',
                'billing_street' => 'Lennox Castle Commercial Chambers',
                'site_street' => 'Loch Sloy Hydro Turbine Hall & Penstocks, Tarbet',
                'assets' => 4600000.00, 'liabilities' => 1450000.00, 'cash' => 690000.00,
            ],
            [
                'company' => 'East Anglian Offshore Wind Support Services Ltd',
                'first' => 'Martin', 'last' => 'Stannard', 'phone' => '01502 555 0155', 'mobile' => '07700 901155',
                'email' => 'mstannard@eastangliaoffshore.co.uk',
                'city' => 'Lowestoft', 'county' => 'Suffolk', 'postcode' => 'NR32 1XG',
                'billing_street' => 'PowerPark Energy Centre, Commercial Road',
                'site_street' => 'Crew Transfer Vessel Quay & High Voltage Tooling Store',
                'assets' => 6100000.00, 'liabilities' => 1950000.00, 'cash' => 910000.00,
            ],
            [
                'company' => 'Humber Hydrogen Infrastructure Ltd',
                'first' => 'Colin', 'last' => 'Gledhill', 'phone' => '01469 555 0156', 'mobile' => '07700 901156',
                'email' => 'cgledhill@humberhydrogen.co.uk',
                'city' => 'Grimsby', 'county' => 'Lincolnshire', 'postcode' => 'DN40 2QU',
                'billing_street' => 'Killingholme Energy Park, Haven Road',
                'site_street' => 'Electrolyser Pilot Plant 1, Humber Bank South',
                'assets' => 7800000.00, 'liabilities' => 2400000.00, 'cash' => 1150000.00,
            ],
            [
                'company' => 'Thames District Heating & CHP Networks Ltd',
                'first' => 'Terence', 'last' => 'Quayle', 'phone' => '0208 555 0157', 'mobile' => '07700 901157',
                'email' => 'tquayle@thamesheating.co.uk',
                'city' => 'Greenwich', 'county' => 'Greater London', 'postcode' => 'SE10 0ES',
                'billing_street' => 'Greenwich Peninsula Energy Centre, Horn Lane',
                'site_street' => 'Combined Heat & Power Turbine Room, Millennium Way',
                'assets' => 8400000.00, 'liabilities' => 2700000.00, 'cash' => 1250000.00,
            ],
            [
                'company' => 'Severn Trent Commercial Water Filtration Ltd',
                'first' => 'Russell', 'last' => 'Barham', 'phone' => '02476 555 0158', 'mobile' => '07700 901158',
                'email' => 'rbarham@severntrentcommercial.co.uk',
                'city' => 'Coventry', 'county' => 'West Midlands', 'postcode' => 'CV1 2LZ',
                'billing_street' => 'Severn Trent Centre, 2 St John\'s Street',
                'site_street' => 'Finham Commercial Water Treatment Plant, St Martins Rd',
                'assets' => 9600000.00, 'liabilities' => 3100000.00, 'cash' => 1400000.00,
            ],
            [
                'company' => 'Tyne Renewable Biomass Energy Ltd',
                'first' => 'Darren', 'last' => 'Hedley', 'phone' => '0191 555 0159', 'mobile' => '07700 901159',
                'email' => 'dhedley@tynebiomass.co.uk',
                'city' => 'South Shields', 'county' => 'Tyne and Wear', 'postcode' => 'NE33 1RQ',
                'billing_street' => 'Riverside Energy Works, Commercial Road',
                'site_street' => 'Biomass Gasifier & Pellet Drying Silo 2, Temple Town',
                'assets' => 3500000.00, 'liabilities' => 1100000.00, 'cash' => 520000.00,
            ],
            [
                'company' => 'Welsh Valleys Solar Energy Cooperatives plc',
                'first' => 'Hywel', 'last' => 'Jenkins', 'phone' => '01443 555 0160', 'mobile' => '07700 901160',
                'email' => 'hjenkins@welshvalleyssolar.co.uk',
                'city' => 'Pontypridd', 'county' => 'Mid Glamorgan', 'postcode' => 'CF37 5UR',
                'billing_street' => 'Treforest Industrial Estate, Main Avenue',
                'site_street' => 'Hillside Solar PV Farm 500kW Inverter Station, Cilfynydd',
                'assets' => 4100000.00, 'liabilities' => 1250000.00, 'cash' => 610000.00,
            ],

            // 61-70: Healthcare, Hospitals, Private Clinics & Pharmaceuticals
            [
                'company' => 'Harley Street Specialist Medical Suites Ltd',
                'first' => 'Dr. Edward', 'last' => 'Chesterfield', 'phone' => '0207 555 0161', 'mobile' => '07700 901161',
                'email' => 'echesterfield@harleymedical.co.uk',
                'city' => 'London', 'county' => 'Greater London', 'postcode' => 'W1G 9PJ',
                'billing_street' => '94 Harley Street Practice Management',
                'site_street' => 'Surgical Theatres & Medical Gas Incomers, Devonshire Pl',
                'assets' => 7200000.00, 'liabilities' => 2100000.00, 'cash' => 1100000.00,
            ],
            [
                'company' => 'Caledonia Private Healthcare & Surgical Clinic Ltd',
                'first' => 'Dr. Fiona', 'last' => 'Guthrie', 'phone' => '0131 555 0162', 'mobile' => '07700 901162',
                'email' => 'fguthrie@caledoniahealth.co.uk',
                'city' => 'Edinburgh', 'county' => 'Midlothian', 'postcode' => 'EH12 6AW',
                'billing_street' => 'Corstorphine Road Medical Pavilion',
                'site_street' => 'Operating Theatres 1 & 2 Laminar Flow AHU Plant, Haymarket',
                'assets' => 5800000.00, 'liabilities' => 1700000.00, 'cash' => 860000.00,
            ],
            [
                'company' => 'Midlands Senior Living & Care Village Group Ltd',
                'first' => 'Rachel', 'last' => 'Blenkinsop', 'phone' => '01926 555 0163', 'mobile' => '07700 901163',
                'email' => 'rblenkinsop@midlandscare.co.uk',
                'city' => 'Leamington Spa', 'county' => 'Warwickshire', 'postcode' => 'CV32 5TY',
                'billing_street' => 'Clarendon Square Corporate Suites',
                'site_street' => 'Oakwood Care Home 80-Bed HVAC & Emergency Generators',
                'assets' => 6400000.00, 'liabilities' => 1950000.00, 'cash' => 950000.00,
            ],
            [
                'company' => 'Manchester Biomedical Research Laboratories Ltd',
                'first' => 'Dr. Nilesh', 'last' => 'Patel', 'phone' => '0161 555 0164', 'mobile' => '07700 901164',
                'email' => 'npatel@manchesterbiomed.co.uk',
                'city' => 'Manchester', 'county' => 'Greater Manchester', 'postcode' => 'M13 9XX',
                'billing_street' => 'Citylabs 2.0, Oxford Road',
                'site_street' => 'BSL-3 Containment Cleanroom & Exhaust Fume Scrubbers',
                'assets' => 8100000.00, 'liabilities' => 2450000.00, 'cash' => 1200000.00,
            ],
            [
                'company' => 'Thames Valley Diagnostics & Pathology Labs Ltd',
                'first' => 'Dr. Anthony', 'last' => 'Harding', 'phone' => '0118 555 0165', 'mobile' => '07700 901165',
                'email' => 'aharding@thamespathology.co.uk',
                'city' => 'Reading', 'county' => 'Berkshire', 'postcode' => 'RG6 6UR',
                'billing_street' => 'Reading Science Park, Pepper Road',
                'site_street' => 'Pathology Laboratory Chiller & Medical Archive Freezers',
                'assets' => 4900000.00, 'liabilities' => 1450000.00, 'cash' => 730000.00,
            ],
            [
                'company' => 'Alderley Edge BioPharma Innovations Ltd',
                'first' => 'Dr. Claire', 'last' => 'Townsend', 'phone' => '01625 555 0166', 'mobile' => '07700 901166',
                'email' => 'ctownsend@alderleypharma.co.uk',
                'city' => 'Alderley Edge', 'county' => 'Cheshire', 'postcode' => 'SK10 4TG',
                'billing_street' => 'Alderley Park, Mereside Campus',
                'site_street' => 'API Synthesis Pilot Plant & Nitrogen Purge Lines',
                'assets' => 9500000.00, 'liabilities' => 2800000.00, 'cash' => 1450000.00,
            ],
            [
                'company' => 'Cambridge Genomics & Gene Therapy Laboratories Ltd',
                'first' => 'Dr. Julian', 'last' => 'Forsyth', 'phone' => '01223 555 0167', 'mobile' => '07700 901167',
                'email' => 'jforsyth@cambridgegenomics.co.uk',
                'city' => 'Cambridge', 'county' => 'Cambridgeshire', 'postcode' => 'CB22 3AT',
                'billing_street' => 'Babraham Research Campus',
                'site_street' => 'Sequencer Server Cleanroom & Cryo-storage -80C Units',
                'assets' => 10500000.00, 'liabilities' => 3100000.00, 'cash' => 1600000.00,
            ],
            [
                'company' => 'Bristol Orthopaedic & Sports Medicine Clinic Ltd',
                'first' => 'Mr. Gregory', 'last' => 'Davenport', 'phone' => '0117 555 0168', 'mobile' => '07700 901168',
                'email' => 'gdavenport@bristolortho.co.uk',
                'city' => 'Bristol', 'county' => 'Somerset', 'postcode' => 'BS8 3JL',
                'billing_street' => 'Clifton Down Medical Practice, 12 Litfield Place',
                'site_street' => 'MRI Scanner Cryocooler & Recovery Wards HVAC',
                'assets' => 4300000.00, 'liabilities' => 1250000.00, 'cash' => 640000.00,
            ],
            [
                'company' => 'Newcastle Health Trust Facilities Provider Ltd',
                'first' => 'Brenda', 'last' => 'Carruthers', 'phone' => '0191 555 0169', 'mobile' => '07700 901169',
                'email' => 'bcarruthers@northeasthealthfm.co.uk',
                'city' => 'Newcastle upon Tyne', 'county' => 'Tyne and Wear', 'postcode' => 'NE7 7DN',
                'billing_street' => 'Freeman Hospital Estates Building, High Heaton',
                'site_street' => 'Cardiothoracic Centre Steam Autoclaves & Medical Vacuum',
                'assets' => 8800000.00, 'liabilities' => 2700000.00, 'cash' => 1300000.00,
            ],
            [
                'company' => 'Yorkshire Hospice & Palliative Care Centres Ltd',
                'first' => 'Valerie', 'last' => 'Houghton', 'phone' => '01423 555 0170', 'mobile' => '07700 901170',
                'email' => 'vhoughton@yorkshirehospice.co.uk',
                'city' => 'Harrogate', 'county' => 'North Yorkshire', 'postcode' => 'HG2 8NA',
                'billing_street' => 'Hookstone Chase Memorial Office',
                'site_street' => 'Inpatient Wing Solar Underfloor Heating & Nurse Call System',
                'assets' => 3600000.00, 'liabilities' => 950000.00, 'cash' => 540000.00,
            ],

            // 71-80: Construction, Roofing & Civil Engineering Contractors
            [
                'company' => 'Balfour Northern Civil Engineering Ltd',
                'first' => 'Gavin', 'last' => 'Strathclyde', 'phone' => '0191 555 0171', 'mobile' => '07700 901171',
                'email' => 'gstrathclyde@balfournorthern.co.uk',
                'city' => 'Sunderland', 'county' => 'Tyne and Wear', 'postcode' => 'SR5 3XZ',
                'billing_street' => 'Doxford International Business Park, Admiral Way',
                'site_street' => 'Plant Yard 4 Heavy Crane & Excavator Workshop, Pallion',
                'assets' => 7800000.00, 'liabilities' => 2600000.00, 'cash' => 1150000.00,
            ],
            [
                'company' => 'Severn Valley Industrial Roofing & Cladding Ltd',
                'first' => 'Wayne', 'last' => 'Tidmarsh', 'phone' => '01905 555 0172', 'mobile' => '07700 901172',
                'email' => 'wtidmarsh@severnroofing.co.uk',
                'city' => 'Worcester', 'county' => 'Worcestershire', 'postcode' => 'WR4 9FA',
                'billing_street' => 'Warndon Business Park, Shire Business Park',
                'site_street' => 'Sheet Metal & Composite Panel Staging Bay 3, Blackpole',
                'assets' => 2900000.00, 'liabilities' => 920000.00, 'cash' => 430000.00,
            ],
            [
                'company' => 'Midlands Groundworks & Civil Foundations Ltd',
                'first' => 'Patrick', 'last' => 'Donnelly', 'phone' => '01543 555 0173', 'mobile' => '07700 901173',
                'email' => 'pdonnelly@midlandsgroundworks.co.uk',
                'city' => 'Cannock', 'county' => 'Staffordshire', 'postcode' => 'WS11 0XG',
                'billing_street' => 'Watling Street Commercial Yard, Norton Canes',
                'site_street' => 'Piling Rig Depot & Fuel Bunkering Facility, Walkmill Lane',
                'assets' => 3600000.00, 'liabilities' => 1150000.00, 'cash' => 540000.00,
            ],
            [
                'company' => 'Thames Estuary Marine Civil Contractors Ltd',
                'first' => 'Barry', 'last' => 'Golding', 'phone' => '01634 555 0174', 'mobile' => '07700 901174',
                'email' => 'bgolding@thamesmarine.co.uk',
                'city' => 'Chatham', 'county' => 'Kent', 'postcode' => 'ME4 4QU',
                'billing_street' => 'Historic Dockyard Corporate Office, Church Lane',
                'site_street' => 'Floating Pontoon Repair Slipway & Diving Tool Store',
                'assets' => 4800000.00, 'liabilities' => 1500000.00, 'cash' => 710000.00,
            ],
            [
                'company' => 'Pennine Demolition & Environmental Remediation Ltd',
                'first' => 'Mick', 'last' => 'Flanagan', 'phone' => '0161 555 0175', 'mobile' => '07700 901175',
                'email' => 'mflanagan@penninedemo.co.uk',
                'city' => 'Salford', 'county' => 'Greater Manchester', 'postcode' => 'M50 3SP',
                'billing_street' => 'Anchorage Quay Commercial House',
                'site_street' => 'Asbestos Decontamination & Crusher Yard, Eccles New Rd',
                'assets' => 3400000.00, 'liabilities' => 1050000.00, 'cash' => 510000.00,
            ],
            [
                'company' => 'Caledonian Structural Glazing & Façades Ltd',
                'first' => 'Euan', 'last' => 'Blair', 'phone' => '0141 555 0176', 'mobile' => '07700 901176',
                'email' => 'eblair@caledoniaglazing.co.uk',
                'city' => 'Glasgow', 'county' => 'Lanarkshire', 'postcode' => 'G32 8RE',
                'billing_street' => 'Clydeside Industrial Park, Fullerton Road',
                'site_street' => 'Curtain Walling Assembly Line, London Road',
                'assets' => 2750000.00, 'liabilities' => 880000.00, 'cash' => 410000.00,
            ],
            [
                'company' => 'Yorkshire Commercial Brickwork & Masonry Ltd',
                'first' => 'Trevor', 'last' => 'Appleyard', 'phone' => '01924 555 0177', 'mobile' => '07700 901177',
                'email' => 'tappleyard@yorkshirebrick.co.uk',
                'city' => 'Wakefield', 'county' => 'West Yorkshire', 'postcode' => 'WF2 0XE',
                'billing_street' => 'Calder Park, Peel Avenue',
                'site_street' => 'Stone Dressing & Precast Yard, Denby Dale Road',
                'assets' => 1950000.00, 'liabilities' => 610000.00, 'cash' => 290000.00,
            ],
            [
                'company' => 'Anglia Specialist Concrete & Piling Ltd',
                'first' => 'Martin', 'last' => 'Boulter', 'phone' => '01473 555 0178', 'mobile' => '07700 901178',
                'email' => 'mboulter@angliaconcrete.co.uk',
                'city' => 'Ipswich', 'county' => 'Suffolk', 'postcode' => 'IP3 9FJ',
                'billing_street' => 'Ransomes Europark, Central Avenue',
                'site_street' => 'Ready-Mix Batching Plant 2, Landseer Road',
                'assets' => 3100000.00, 'liabilities' => 990000.00, 'cash' => 460000.00,
            ],
            [
                'company' => 'South Coast Timber Framing & Glulam Ltd',
                'first' => 'Dominic', 'last' => 'Hawkins', 'phone' => '01243 555 0179', 'mobile' => '07700 901179',
                'email' => 'dhawkins@southcoasttimber.co.uk',
                'city' => 'Chichester', 'county' => 'West Sussex', 'postcode' => 'PO19 8TY',
                'billing_street' => 'Chichester Trade Park, Terminus Road',
                'site_street' => 'Precision Timber Frame Workshop, Quarry Lane',
                'assets' => 2200000.00, 'liabilities' => 690000.00, 'cash' => 330000.00,
            ],
            [
                'company' => 'Bristol Acoustic Ceiling & Partitioning Ltd',
                'first' => 'Nigel', 'last' => 'Vaughan', 'phone' => '0117 555 0180', 'mobile' => '07700 901180',
                'email' => 'nvaughan@bristolceilings.co.uk',
                'city' => 'Bristol', 'county' => 'Somerset', 'postcode' => 'BS4 5PF',
                'billing_street' => 'St Philips Trade Park, Albert Road',
                'site_street' => 'Commercial Drylining Warehouse Unit 7, Feeder Road',
                'assets' => 1750000.00, 'liabilities' => 540000.00, 'cash' => 260000.00,
            ],

            // 81-90: IT Data Centers, Tech Parks & Telecommunications
            [
                'company' => 'Slough Trading Estate Hyperscale Data Centers Ltd',
                'first' => 'Rajesh', 'last' => 'Venkatesh', 'phone' => '01753 555 0181', 'mobile' => '07700 901181',
                'email' => 'rvenkatesh@sloughdatacenter.co.uk',
                'city' => 'Slough', 'county' => 'Berkshire', 'postcode' => 'SL1 4DX',
                'billing_street' => 'Buckingham Avenue Corporate Hub',
                'site_street' => 'Data Hall 4 Chilled Water CRAC Units & DRUPS Rotary Generators',
                'assets' => 18500000.00, 'liabilities' => 5800000.00, 'cash' => 2900000.00,
            ],
            [
                'company' => 'London Docklands Telehouse Colocation plc',
                'first' => 'Jason', 'last' => 'Kowalski', 'phone' => '0207 555 0182', 'mobile' => '07700 901182',
                'email' => 'jkowalski@telehouselondon.co.uk',
                'city' => 'London', 'county' => 'Greater London', 'postcode' => 'E14 2AA',
                'billing_street' => 'Coriander Avenue Data Campus',
                'site_street' => 'North Building 11kV Substation & In-Row Cooling Systems',
                'assets' => 22000000.00, 'liabilities' => 6900000.00, 'cash' => 3500000.00,
            ],
            [
                'company' => 'Manchester MediaCityUK Broadcast Facilities Ltd',
                'first' => 'Gillian', 'last' => 'Swain', 'phone' => '0161 555 0183', 'mobile' => '07700 901183',
                'email' => 'gswain@mediacityfm.co.uk',
                'city' => 'Salford', 'county' => 'Greater Manchester', 'postcode' => 'M50 2EQ',
                'billing_street' => 'The Greenhouse, Broadway',
                'site_street' => 'Studio 1-5 Production Galleries Acoustic HVAC & UPS',
                'assets' => 12500000.00, 'liabilities' => 3800000.00, 'cash' => 1950000.00,
            ],
            [
                'company' => 'Cambridge Silicon Fen Science Park Ltd',
                'first' => 'Marcus', 'last' => 'Hetherington', 'phone' => '01223 555 0184', 'mobile' => '07700 901184',
                'email' => 'mhetherington@siliconfen.co.uk',
                'city' => 'Cambridge', 'county' => 'Cambridgeshire', 'postcode' => 'CB4 0EY',
                'billing_street' => 'Cambridge Science Park, Milton Road',
                'site_street' => 'Bio-Innovation Tech Incubator Cleanrooms, Cowley Road',
                'assets' => 15000000.00, 'liabilities' => 4700000.00, 'cash' => 2350000.00,
            ],
            [
                'company' => 'Edinburgh BioQuarter Tech Campus Ltd',
                'first' => 'Kirsten', 'last' => 'McFarlane', 'phone' => '0131 555 0185', 'mobile' => '07700 901185',
                'email' => 'kmcfarlane@bioquarterfm.co.uk',
                'city' => 'Edinburgh', 'county' => 'Midlothian', 'postcode' => 'EH16 4UX',
                'billing_street' => 'Nine BioQuarter, 9 Little France Road',
                'site_street' => 'Medical Genomics Server Farm & Cryogenic Tank Yard',
                'assets' => 9400000.00, 'liabilities' => 2900000.00, 'cash' => 1450000.00,
            ],
            [
                'company' => 'Thames Valley Fiber Optic Networks Ltd',
                'first' => 'Luke', 'last' => 'Bradshaw', 'phone' => '0118 555 0186', 'mobile' => '07700 901186',
                'email' => 'lbradshaw@thamesfiber.co.uk',
                'city' => 'Reading', 'county' => 'Berkshire', 'postcode' => 'RG2 6TG',
                'billing_street' => 'Green Park Commercial Centre, South Oak Way',
                'site_street' => 'Regional Fiber Exchange POP Node 5, Brook Drive',
                'assets' => 6700000.00, 'liabilities' => 2100000.00, 'cash' => 1050000.00,
            ],
            [
                'company' => 'Leeds South Bank Innovation Hubs Ltd',
                'first' => 'Zoe', 'last' => 'Kitson', 'phone' => '0113 555 0187', 'mobile' => '07700 901187',
                'email' => 'zkitson@leedssouthbank.co.uk',
                'city' => 'Leeds', 'county' => 'West Yorkshire', 'postcode' => 'LS10 1HD',
                'billing_street' => 'Round Foundry Media Centre, Foundry Street',
                'site_street' => 'Fintech Co-working Space Air Conditioning & Access Systems',
                'assets' => 4500000.00, 'liabilities' => 1350000.00, 'cash' => 710000.00,
            ],
            [
                'company' => 'Cardiff Central Telecoms Data Center Ltd',
                'first' => 'Dewi', 'last' => 'Evans', 'phone' => '02920 555 0188', 'mobile' => '07700 901188',
                'email' => 'devans@cardiffdatacenter.co.uk',
                'city' => 'Cardiff', 'county' => 'South Glamorgan', 'postcode' => 'CF10 5LE',
                'billing_street' => 'Central Square Tower, Wood Street',
                'site_street' => 'Telco Exchange Colocation Hall 2, Dumballs Road',
                'assets' => 5900000.00, 'liabilities' => 1800000.00, 'cash' => 920000.00,
            ],
            [
                'company' => 'Newcastle Helix Innovation District Ltd',
                'first' => 'Ross', 'last' => 'Stephenson', 'phone' => '0191 555 0189', 'mobile' => '07700 901189',
                'email' => 'rstephenson@newcastlehelix.co.uk',
                'city' => 'Newcastle upon Tyne', 'county' => 'Tyne and Wear', 'postcode' => 'NE4 5TG',
                'billing_street' => 'The Core, Science Square, Bath Lane',
                'site_street' => 'Urban Sciences Building Smart Grid Energy Centre',
                'assets' => 7300000.00, 'liabilities' => 2200000.00, 'cash' => 1100000.00,
            ],
            [
                'company' => 'Belfast Catalyst Tech Incubation Park Ltd',
                'first' => 'Conor', 'last' => 'McAleese', 'phone' => '02890 555 0190', 'mobile' => '07700 901190',
                'email' => 'cmcaleese@catalystbelfast.co.uk',
                'city' => 'Belfast', 'county' => 'County Antrim', 'postcode' => 'BT3 9DT',
                'billing_street' => 'Catalyst Inc, The Innovation Centre, Queens Road',
                'site_street' => 'Software R&D Pavilion Server Room Cooling & Fire Suppression',
                'assets' => 4800000.00, 'liabilities' => 1450000.00, 'cash' => 750000.00,
            ],

            // 91-100: Food, Beverage & Agribusiness Facilities
            [
                'company' => 'Caledonian Breweries & Distilleries Group plc',
                'first' => 'Archibald', 'last' => 'MacIntyre', 'phone' => '0131 555 0191', 'mobile' => '07700 901191',
                'email' => 'amacintyre@caledonianbeer.co.uk',
                'city' => 'Edinburgh', 'county' => 'Midlothian', 'postcode' => 'EH11 1DF',
                'billing_street' => 'Slateford Road Brewhouse',
                'site_street' => 'Fermentation Vessel Cooling Jacket Loop & Steam Boilers',
                'assets' => 8400000.00, 'liabilities' => 2600000.00, 'cash' => 1350000.00,
            ],
            [
                'company' => 'Yorkshire Artisan Dairy & Cheesemakers Ltd',
                'first' => 'Malcolm', 'last' => 'Wensley', 'phone' => '01969 555 0192', 'mobile' => '07700 901192',
                'email' => 'mwensley@yorkshiredairy.co.uk',
                'city' => 'Hawes', 'county' => 'North Yorkshire', 'postcode' => 'DL8 3RN',
                'billing_street' => 'Wensleydale Creamery Road Corporate Suites',
                'site_street' => 'Cheese Maturation Cellars Climate Controlled Rooms 1-6',
                'assets' => 3200000.00, 'liabilities' => 980000.00, 'cash' => 490000.00,
            ],
            [
                'company' => 'Lincolnshire Farm Produce & Packhouse plc',
                'first' => 'Graham', 'last' => 'Brocklehurst', 'phone' => '01205 555 0193', 'mobile' => '07700 901193',
                'email' => 'gbrocklehurst@lincolnproduce.co.uk',
                'city' => 'Boston', 'county' => 'Lincolnshire', 'postcode' => 'PE21 7TW',
                'billing_street' => 'Marsh Lane Industrial Estate, Bittern Way',
                'site_street' => 'Cold Hydrocooling Dip & Vegetable Grading Line 2',
                'assets' => 5800000.00, 'liabilities' => 1750000.00, 'cash' => 890000.00,
            ],
            [
                'company' => 'Kent Orchard Cider & Juice Bottling Ltd',
                'first' => 'Jeremy', 'last' => 'Broadmead', 'phone' => '01622 555 0194', 'mobile' => '07700 901194',
                'email' => 'jbroadmead@kentcider.co.uk',
                'city' => 'Maidstone', 'county' => 'Kent', 'postcode' => 'ME14 2LE',
                'billing_street' => 'Medway Valley Commercial Park, Beddow Way',
                'site_street' => 'Automated Bottling Line 1 Pasteuriser & Air Compressors',
                'assets' => 2900000.00, 'liabilities' => 890000.00, 'cash' => 450000.00,
            ],
            [
                'company' => 'Somerset Cheddar Creameries & Cold Storage Ltd',
                'first' => 'Clive', 'last' => 'Babbington', 'phone' => '01935 555 0195', 'mobile' => '07700 901195',
                'email' => 'cbabbington@somersetcheddar.co.uk',
                'city' => 'Yeovil', 'county' => 'Somerset', 'postcode' => 'BA22 8RZ',
                'billing_street' => 'Yeovil Trade Park, Houndstone Business Park',
                'site_street' => 'Pasteurisation Heat Exchanger & Ammonia Refrigeration Plant',
                'assets' => 4300000.00, 'liabilities' => 1350000.00, 'cash' => 660000.00,
            ],
            [
                'company' => 'Aberdeenshire Seafood Smokehouse & Export Ltd',
                'first' => 'Hamish', 'last' => 'Strachan', 'phone' => '01779 555 0196', 'mobile' => '07700 901196',
                'email' => 'hstrachan@aberdeenseafood.co.uk',
                'city' => 'Peterhead', 'county' => 'Aberdeenshire', 'postcode' => 'AB42 1NR',
                'billing_street' => 'Harbour Street Processing Chambers',
                'site_street' => 'Smoker Kilns Extraction, Flake Ice Plant & Filleting Hall',
                'assets' => 3700000.00, 'liabilities' => 1100000.00, 'cash' => 580000.00,
            ],
            [
                'company' => 'Cornish Pasty Baking Co. Central Bakeries Ltd',
                'first' => 'Tristan', 'last' => 'Penhaligon', 'phone' => '01209 555 0197', 'mobile' => '07700 901197',
                'email' => 'tpenhaligon@cornishpastyco.co.uk',
                'city' => 'Redruth', 'county' => 'Cornwall', 'postcode' => 'TR15 3RR',
                'billing_street' => 'Pool Industrial Estate, Wilson Way',
                'site_street' => 'Tunnel Ovens Gas Extraction & Spiral Blast Freezers',
                'assets' => 3100000.00, 'liabilities' => 950000.00, 'cash' => 480000.00,
            ],
            [
                'company' => 'Warwickshire Organic Milling & Grain Silos Ltd',
                'first' => 'Neville', 'last' => 'Shirley', 'phone' => '01789 555 0198', 'mobile' => '07700 901198',
                'email' => 'nshirley@warwickorganic.co.uk',
                'city' => 'Stratford-upon-Avon', 'county' => 'Warwickshire', 'postcode' => 'CV37 9NQ',
                'billing_street' => 'Masons Road Industrial Estate, Western Road',
                'site_street' => 'Grain Elevator Dust Suppression & Flour Silo Ventilation',
                'assets' => 2600000.00, 'liabilities' => 810000.00, 'cash' => 390000.00,
            ],
            [
                'company' => 'Belfast Craft Distillers & Bonded Warehouses Ltd',
                'first' => 'Sean', 'last' => 'MacBride', 'phone' => '02890 555 0199', 'mobile' => '07700 901199',
                'email' => 'smacbride@belfastdistillers.co.uk',
                'city' => 'Belfast', 'county' => 'County Antrim', 'postcode' => 'BT1 3EF',
                'billing_street' => 'Cathedral Quarter Historic Bond, Donegall Street',
                'site_street' => 'Copper Pot Still Condenser Cooling & Cask Staging Cellar',
                'assets' => 4900000.00, 'liabilities' => 1500000.00, 'cash' => 760000.00,
            ],
            [
                'company' => 'Staffordshire Oatcake & Food Packaging Ltd',
                'first' => 'Darren', 'last' => 'Mountford', 'phone' => '01782 555 0200', 'mobile' => '07700 901200',
                'email' => 'dmountford@staffordshirefood.co.uk',
                'city' => 'Stoke-on-Trent', 'county' => 'Staffordshire', 'postcode' => 'ST4 2RT',
                'billing_street' => 'Festival Park, Ridgehouse Drive',
                'site_street' => 'Commercial Griddle Lines & Clean Packaging Cleanroom 3',
                'assets' => 1800000.00, 'liabilities' => 560000.00, 'cash' => 280000.00,
            ],
        ];

        $countCreated = 0;
        foreach ($companies as $i => $data) {
            $customer = Customer::firstOrCreate(
                ['company_name' => $data['company']],
                [
                    'contact_firstname' => $data['first'],
                    'contact_lastname' => $data['last'],
                    'contact_phone' => $data['phone'],
                    'contact_mobile' => $data['mobile'],
                    'contact_email' => $data['email'],
                    'status' => 'active',
                ]
            );

            // Customer Financial Details
            $regNumber = sprintf('%08d', 10000000 + ($i + 1) * 37);
            $netAssets = $data['assets'] - $data['liabilities'];
            CustomerDetails::updateOrCreate(
                ['customer_id' => $customer->id],
                [
                    'company_name' => $data['company'],
                    'registration_number' => $regNumber,
                    'assets' => $data['assets'],
                    'net_assets' => $netAssets,
                    'liabilities' => $data['liabilities'],
                    'cash_in_bank' => $data['cash'],
                ]
            );

            // Billing Address
            CustomerAddress::updateOrCreate(
                ['customer_id' => $customer->id, 'address_type' => 'billing'],
                [
                    'contact_firstname' => $data['first'],
                    'contact_lastname' => $data['last'],
                    'contact_phone' => $data['phone'],
                    'contact_mobile' => $data['mobile'],
                    'contact_email' => $data['email'],
                    'address' => $data['billing_street'],
                    'county' => $data['county'],
                    'postcode' => $data['postcode'],
                    'country' => 'United Kingdom',
                    'location' => $data['city'],
                    'status' => 'active',
                    'default' => 'yes',
                ]
            );

            // Site Address
            CustomerAddress::updateOrCreate(
                ['customer_id' => $customer->id, 'address_type' => 'site'],
                [
                    'contact_firstname' => $data['first'],
                    'contact_lastname' => $data['last'],
                    'contact_phone' => $data['phone'],
                    'contact_mobile' => $data['mobile'],
                    'contact_email' => $data['email'],
                    'address' => $data['site_street'],
                    'county' => $data['county'],
                    'postcode' => $data['postcode'],
                    'country' => 'United Kingdom',
                    'location' => $data['city'],
                    'status' => 'active',
                    'default' => 'no',
                ]
            );

            $countCreated++;
        }

        $this->command->info("Successfully seeded {$countCreated} customer records with addresses and financials.");
    }
}
